In [1]:
from src import metadataextraction as md
from src import objdect as ob
import matplotlib.pyplot as plt
import numpy as np

Fluorescence micropscopy: `3288-1-AP-OP.czi`

In [2]:
filepath = "D:/TFM/Microscopy/video/3288-1-AP-OP.czi"
# 1. Exploring 3288-1 czi file
czi = md.openczi(filepath)
 # Image dimension
dims = md.dimensions(czi)
print(dims)
 # Channel information
first_channel, second_channel, third_channel = md.image_info(czi)
print(first_channel)
print(second_channel)
print(third_channel)
 # Metadata function from czifile library
xml_metadata = md.basic_metadata(filepath)
 # Image timeseries
timeseries = md.timeseries(filepath)
 # Open image
img = md.img(filepath)

(201, 3, 1, 940, 940)
[[[1 1 1 ... 2 2 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 2 2 2]]]
[[[2 2 1 ... 1 1 1]
  [1 2 1 ... 1 1 1]
  [2 2 2 ... 3 2 1]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 2 2 ... 0 2 2]]]
[[[1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 2 3 ... 3 2 2]
  ...
  [1 1 1 ... 0 1 1]
  [2 1 1 ... 0 0 0]
  [3 1 0 ... 0 0 0]]]


In [8]:
# 2. Extraction of metadata and dataframe creation
def czi3288():
    # Image type
    img_type = md.get_imgtype("3288-1-AP-OP.czi")
    print(f'Image type:', img_type)
    # Metadata
    metadata = md.get_metadata("D:/TFM/Microscopy/video/3288-1-AP-OP.czi")
    print(f'Object data type is:', type(metadata))
    print(metadata[0])
    print(metadata[1])
    # Additional information
    md1 = md.get_additional_metadata_czi("D:/TFM/Microscopy/video/3288-1-AP-OP.czi")
    print(f'Additional metadata:', md1)
    # Convert information into a dataframe 
    df= md.md2dataframe(metadata[0], paramcol='Parameter', keycol='Value')
    print(df)
    # More information 
    czi_array = md.get_array_czi("D:/TFM/Microscopy/video/3288-1-AP-OP.czi", metadata[0])
    print(f'Czi array:', czi_array)
    # XML format
    md.writexml_czi("D:/TFM/Microscopy/video/3288-1-AP-OP.czi", xmlsuffix='_CZI_MetaData.xml')

    return metadata

metadata = czi3288()

This file extension is code-supported
Image type: czi
This file extension is code-supported
Image Type:  czi
<class 'dict'>
<class 'dict'>
<class 'dict'>
Key not found: 'Magnification'
<class 'dict'>
Trying to extract Scene and Well information if existing ...
<class 'dict'>
Object data type is: <class 'tuple'>
{'Directory': 'D:/TFM/Microscopy/video', 'Filename': '3288-1-AP-OP.czi', 'Extension': 'czi', 'ImageType': 'czi', 'Name': None, 'AcqDate': '2023-12-04T16:26:28.502799Z', 'TotalSeries': None, 'SizeX': 940, 'SizeY': 940, 'SizeZ': 1, 'SizeC': 3, 'SizeT': 201, 'Sizes BF': None, 'Axes': 'STCZYX0', 'Shape': (1, 201, 3, 1, 940, 940, 1), 'isRGB': None, 'ObjNA': 1.4, 'ObjMag': None, 'ObjID': 'Objective:1', 'ObjName': 'Plan-Apochromat 63x/1.40 Oil DIC M27', 'ObjImmersion': 'Oil', 'XScale': 0.071, 'YScale': 0.071, 'ZScale': 0.071, 'XScaleUnit': 'µm', 'YScaleUnit': 'µm', 'ZScaleUnit': 'µm', 'DetectorModel': [None, None], 'DetectorName': ['Airyscan', 'LSM 980'], 'DetectorType': ['GaAsP-PMT', 